### ISSUE TITLE
CodeMirror hints window re-renders when trying to navigate down it (CSS)

### ISSUE THREAD

**Issue by sarahrooney** [netizenorg/netitor#11]
Found on Safari, Firefox, and Chrome.
Possibly due to the async _update() function running every second or so. i think continuing to type while the CM hints window is already open triggers this issue.

Steps to reproduce:
1) write CSS in a <style> tag as you would regularly
2) wait for CM hints window to open while writing a property
3) navigate down the list with ur arrow key; this should work fine. then continue typing out the rest of your property manually
4) try navigating down the list again while you type out the rest of the property. active selection should keep bouncing to the top of the list.

low priority
can be fixed by navigating elsewhere with your arrow keys and "manually" re-triggering the hints window

**Comment by nbriz** [comment]
thnx for catching this!

**Comment by nbriz** [comment]
ur hunch was right, issue was in the `async _update()` just fixed it, pushing changes now
